### ISSUE TITLE
Event Gallery

### ISSUE THREAD

**Issue by VinayakTekade** [aravindvnair99/AYKYA-Fest#13]
### Stage 1
- [x] Hamburger with navbar
- [x] Cards to show previous events
    - [x] Clicking on the card shows details about the event
- [x] Footer

### Stage 2
- [x] Add all events to events list page
- [x] Add content to every event page

**Comment by Subaharish** [comment]
@VinayakTekade   Only 3 events they gave, so I added that contents only
